### PR TITLE
Ico image

### PR DESCRIPTION
**Pull request by chrissimpkins**
This PR:

1. adds a new PNG windows installer icon image file
2. adds a new shell script (`img/icoconv.sh`) that automates conversion from png to multi size ico file for Windows platform
3. adds a new ico file for the Windows installer.

All changes are contained in the new `img` directory at the top level of the repository.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
👍

**Comment by chrissimpkins** [comment]
@texhex let me know if there are any issues with that .ico image file.  It should support all sizes that you need.

**Comment by texhex** [comment]
Will do, but so far everything is looking perfect.

**Comment by chrissimpkins** [comment]
👍

**Pull request merged**
